// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCtXRLwW3wgIvmsj4NIiTxThFhXucGVkY',
    appId: '1:827019702547:web:5bea002aef203a7f4ceae6',
    messagingSenderId: '827019702547',
    projectId: 'whales-spent',
    authDomain: 'whales-spent.firebaseapp.com',
    storageBucket: 'whales-spent.firebasestorage.app',
    measurementId: 'G-2ZFZ5F3XLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaaiPVgowMVnSpTK_BWytgetjMVudsCd0',
    appId: '1:827019702547:android:5fb6c216607412314ceae6',
    messagingSenderId: '827019702547',
    projectId: 'whales-spent',
    storageBucket: 'whales-spent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZmC5pJPJxG6gaiPF_daSemnuhh1y7dk',
    appId: '1:827019702547:ios:20e6852f14e5f3644ceae6',
    messagingSenderId: '827019702547',
    projectId: 'whales-spent',
    storageBucket: 'whales-spent.firebasestorage.app',
    androidClientId: '827019702547-8hc6ehihsuv5ggdeknesrnnoun185qp9.apps.googleusercontent.com',
    iosClientId: '827019702547-kfvj2bkvi8pi0t1da1imr2tbsrba39fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQlct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZmC5pJPJxG6gaiPF_daSemnuhh1y7dk',
    appId: '1:827019702547:ios:20e6852f14e5f3644ceae6',
    messagingSenderId: '827019702547',
    projectId: 'whales-spent',
    storageBucket: 'whales-spent.firebasestorage.app',
    androidClientId: '827019702547-8hc6ehihsuv5ggdeknesrnnoun185qp9.apps.googleusercontent.com',
    iosClientId: '827019702547-kfvj2bkvi8pi0t1da1imr2tbsrba39fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQlct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCtXRLwW3wgIvmsj4NIiTxThFhXucGVkY',
    appId: '1:827019702547:web:e21399145ada8bbc4ceae6',
    messagingSenderId: '827019702547',
    projectId: 'whales-spent',
    authDomain: 'whales-spent.firebaseapp.com',
    storageBucket: 'whales-spent.firebasestorage.app',
    measurementId: 'G-BV17MJ5R8Z',
  );
}
